### ISSUE TITLE
Conflicting program name

### ISSUE THREAD

**Issue by drws** [marlam/tgd-mirror#1]
Author of TAD from 2019, I present you Tad from 2016:

https://github.com/antonycourtney/tad
https://www.tadviewer.com/

I don't have any affiliation with its authors, but I see that Tad had the name first, already in 2016. The decision to use a very-similar name is leading to issues such as [`tad`](https://aur.archlinux.org/packages/tad)/[`tad-git`](https://aur.archlinux.org/packages/tad-git) vs. [`tad-bin`](https://aur.archlinux.org/packages/tad-bin) in the AUR. Please make your decision more responsible, however you can. What's wrong with `libtad`? :smiley:

**Comment by marlam** [comment]
I renamed TAD to TGD.
